version: '3.9'

services:
  database:
    image: postgres
    container_name: backend-typescript-api
    restart: always
    ports:
      - 5500:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=backend-typescript-api
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
